Migrate to DB_URL, add caching in dockerbuilds
Tech-With-Tim/cdn pull request #10
Opened 2021-07-13 10:29 UTC by Correct-skill

## Summary

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [x] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-24 11:56 UTC, Shubhaankar-Sharma commented
:mhm: m7 when???

2021-07-24 20:11 UTC, SylteA requested changes

2021-07-24 20:11 UTC, SylteA commented on .github/workflows/lint-test.yml
> +          DB_URI: postgres://root:mysecret@localhost:5432/cdn?sslmode=disable
Can we please use constants for this over all repositories?

postgres://twt:twt@postgres:5432/twt

2021-07-24 20:11 UTC, SylteA commented on codecov.yml
> +        target: 50%
target slowly decreasing :3

2021-07-25 11:52 UTC, SylteA approved these changes

2021-07-25 12:12 UTC, Shubhaankar-Sharma commented
m7md let me know when you update credentials

2021-07-27 19:23 UTC, merged