Attempt to achieve #1
Tech-With-Tim/cdn pull request #5
Opened 2021-06-25 22:27 UTC by SnowballSH

## Summary

1. Some small code cleaning because my IDE doesn't like the old code :( Feel free to tell me to undo it if you don't like the change.
2. Attempt to create endpoint /manage/{id/url}.

/manage/{id} is not finished yet, waiting for @Correct-skill 's response on how to differentiate id and url.
New endpoint is tested.

Example: `GET http://localhost:5000/manage/aa.png` => `{"id":6807691003781186055,"name":"bruh"}`

## Checklist

- [x] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [x] I have updated the tests to support the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-26 06:20 UTC, Correct-skill approved these changes
Seems fine :), just edited the error message cause the m7md doesn't like caps and also go-lint doesn't like caps errors, waiting for GET: /manage/{id}

2021-06-26 06:21 UTC, Correct-skill commented
Maybe we can try to improve coverage by checking errors in you handler?

2021-06-26 06:25 UTC, Correct-skill commented
> Merging #5 (e957178) into main (fb8e815) will increase coverage by 1.23%.
> The diff coverage is 50.00%.
So basically, we covered only half of the lines you wrote and we need to achieve atleast 69 percent to get approved by codecov as 69% was the coverage before 👍

2021-06-26 16:57 UTC, SnowballSH commented
Alright. Thanks sponge! I'll do that.

2021-06-26 17:03 UTC, SnowballSH commented
> Maybe we can try to improve coverage by checking errors in you handler?

Ah right. I totally forgot to test the failure part 😂 Sorry about that and I'll do that soon

2021-06-26 20:37 UTC, SnowballSH commented
I finished the two endpoints. The test coverage is too long that I have no idea if I did a good job covering. I added testing for not found and invalid id for my two endpoints.

2021-06-27 02:46 UTC, Correct-skill commented
😂 i Get what you were saying in discord, I added creator id in the get url details query , when I saw that GetDetailsById was returning creator id...

2021-06-27 03:01 UTC, Correct-skill commented on api/handlers_test.go
> +
`require.Equal(t, AssetDetails.CreatorID, manageURLResponse.CreatorID)`

2021-06-27 03:03 UTC, Correct-skill requested changes
Yup just this needs to be add, I generated the sqlc query

2021-06-27 19:17 UTC, SnowballSH commented
Alright, thanks!

2021-06-27 21:21 UTC, SnowballSH commented
Should do now :)

2021-06-28 01:28 UTC, Correct-skill approved these changes

2021-06-28 01:30 UTC, merged